PerlDancer/Dancer2

- lib/Dancer2/Core/App.pm
- t/issues/gh-762.t
- t/issues/gh-762/views/404.tt
If the request dispatch fails to match any route, render any error template before cleaning up the app context, then immediately return the rendered (error) response.
This is as close to using 'local' vars for scoping as we can get, without actually using localized vars.
Resolves #762.
> Improve scoping of app cleanup after dispatch (#762)

- t/classes/Dancer2-Core-Role-StandardResponses/with.t
The test relied on Moo classes without any attributes storing everything
given to their constructor.  This will be changed with a future version
of Moo.  Instead, create the appropriate attributes for the test class.
> Add missing attributes for test class

- lib/Dancer2/Core/App.pm
- t/issues/memleak/die_in_hooks.t
If a hook fails, we croak without cleaning up. This means we're
still holding on to a reference. We should first clean everything
and only then croak.
We could also start using local() there more so the Perl interpreter
cleans up that part.
Test included.
> Fix a memory leak with hook failures:

- lib/Dancer2/Core/App.pm
As far as I can tell, the documentation for ```forward``` is incorrect. This patch fixes it.
> Fix documentation for forward

- lib/Dancer2/Manual/Testing.pod
`$cookie_jar->add_cookie_header` is a noop if request only contains path.
Having spent some time banging my head against the wall I'd prefer if future users don't have to go through the same pain.
> fix testing with cookies example to use full URLs

- t/classes/Dancer2-Core-Request/new.t
- t/config.yml
- t/hooks.t
- t/request.t
- t/request_upload.t
- t/serializer_mutable.t
- t/session_object.t
Simple change to use `note` instead of `diag` in tests to produce cleaner non-verbose output.
Also set the default `Logger` in `t/config.yml` to `Note`. (At least now `Dancer2::Logger::Note` will also get used for some tests)
> Replace Test::More diag with note for cleaner test output

- t/logger_console.t
On Windows, `\` is the directory separator. Therefore, when `t\logger_console.t` is interpolated into a regex pattern, it becomes `tlogger_console.t`,
causing the match, and consequently, the tests in that file to fail.
Even on other platforms, the regex contains two unescaped dots, which, strictly speaking, is not correct.
The solution is to use `\Q$file\E` when interpolating a variable `$file` in to a regex pattern, and use a literal dot in the line number expression.
> GH #947: Tests fail due to unescaped file paths in regex pattern

- lib/Dancer2/Tutorial.pod
File::Slurp is broken, especially in its handling of encoding (see http://blogs.perl.org/users/leon_timmermans/2015/08/fileslurp-is-broken-and-wrong.html, https://rt.cpan.org/Public/Bug/Display.html?id=83126, https://rt.cpan.org/Public/Dist/Display.html?Status=Active;Name=File-Slurp). We shouldn't be recommending it in tutorials.
> Replace File::Slurp (broken) with File::Slurper in Tutorial.pod

- lib/Dancer2/Manual.pod
Add a missing semicolon in a documentation hook example.
> Add missing semicolon in docs example

- lib/Dancer2/CLI/Command/gen.pm
- lib/Dancer2/Manual.pod
This option allows having custom skeleton directories for new applications. Although it's a very simple solution it can save a lot of work for anyone that creates a lot of applications and has to make the same changes every time (eg. use template toolkit instead of simple templates, add bootstrap).
> Add option for providing skeleton

- lib/Dancer2/Core/Role/Template.pm
- t/template_default_tokens.t
From perlvar:
$OLD_PERL_VERSION
$]      See "$^V" for a more modern representation of the Perl version
that allows accurate string comparisons.
Before:
5.018002
After:
v5.18.2
> Use $^V for version in template token, not $]:

- lib/Dancer2/Core/Request.pm
- t/issues/gh-931.t
When merging variables, body parameters overwrite query paraemeters,
but they would both overwrite the route parameters.
This commit makes sure (and adds a test to make sure) that route
parameters will not be overwritten.
This addresses GH #931, except it doesn't allow the query
parameters to overwrite the body.
Seems like Express.js does Query > Body, and Rails does Body > Query
and it's probably - if anything - not RFC compliant to begin with.
> Route parameters should overwrite all other merged variables

- lib/Dancer2/Plugin.pm
Per https://github.com/PerlDancer/Dancer2/issues/990, register_plugin()
no longer should state what versions of Dancer the plugin is to be
registered for. Also removed the deprecation note - leaving it in would
be potentially confusing for new plugin authors.
> Remove deprecated functionality from example plugin.

- lib/Dancer2/Core/App.pm
- lib/Dancer2/Core/DSL.pm
- lib/Dancer2/Core/Request.pm
- t/dsl/parameters.t
- tools/perf.pl
Finally it's landed.
This PR provides three new keywords:
query_parameters
body_parameters
route_parameters
It returns a `Hash::MultiValue` object which you can use in order to get values without worrying about context.
GET /?foo=bar&foo=baz
get '/' => sub {
my $foo = params('query')->{'foo');
ref $foo eq 'ARRAY' and $foo = $foo->[ $#foo ]; # we have to normalize $foo - yuck!
my $foo = query_parameters->get('foo'); # always a single value
my @foo = query_parameters->get_all('foo'); # always array, even if only one value
};
<3
The reason we introduce these keywords instead of a `parameters` keyword is that we want users to make sure they know where they get the parameters and don't accidentally have overwritten merged parameters from multiple sources (and have to know how they are merged). …
> Provide keywords for Hash::MultiValue parameters

- dist.ini
Dancer2::Core::Role::SessionFactory depends on Digest::SHA, which was
added to core in perl v5.9.3. Explicitly add it as a dependency for perl
5.8.x support.
> Add Digest::SHA to prereqs

- lib/Dancer2/Core/Role/Logger.pm
- t/logger.t
The hook names were defined, but they were never called. 
Call them in an around modifier on the log method (similar to where session engine hooks are called). Either being lazy or wise; these hooks are passed the logging engine object, and all params to the log method.
Tests include an example of changing the log level before the message is passed to the logger.
> Call engine.logger.* hooks around logging a message

- Changes
When Dancer2::Plugin2 branch was merged, no changelog entry was added.
Time to make amends for that, before a release is made. :)
> Changelog entry for merge of Dancer2::Plugin2

- lib/Dancer2/Core/Request.pm
Private methods are, well private. The may change.
The Plack 1.0040 (TRIAL) release removes the _parse_query method which
we were calling. Far safer to call the overridden public method via SUPER.
(Similar fix to #1148 for body params)
> Don't call private method for Request query params 

- t/lib/Dancer2/Plugin/DancerPlugin.pm
- t/lib/Dancer2/Plugin/FooPlugin.pm
As pointed out by @veryrusty we have some plugin tests that are using deprecated methods.
- Stop using `plugin_args` and `hook`
- Call `request` as `app->request`.
> Update plugin tests to stop deprecation warnings.

- lib/Dancer2/Core/Request.pm
and report errors when dynamically creating subs.
Fixes https://github.com/PerlDancer/Dancer2/issues/1185
> don't use barewords under use strict

- lib/Dancer2/Core/Role/SessionFactory/File.pm
- t/session_bad_client_cookie.t
Similar test should be added to all session engines.
> Session::YAML should not accept bad session cookie value from client

- dist.ini
Now newer version will be acceptable including 1.17 which does not break D2.
> Simplify YAML version range dep using != 1.16

- lib/Dancer2/Core/Request.pm
According to the `Dancer2::Config` documentation, the configuration option name is `behind_proxy`.
> Fix config option name in Dancer2::Core::Request documentation

- lib/Dancer2/Manual/Deployment.pod
Add the behind_proxy configuration option in the Deployment Manual.
Related with issue https://github.com/PerlDancer/Dancer2/issues/1166
> Add behind_proxy config option to deployment manual

- Changes
- dist.ini
The `pair*` functionals used in Dancer2::Core::HTTP were introduced in List::Util v1.29.
Specify this as the minimum version of List::Util we require.
> Minimum version for List::Util

- lib/Dancer2/Core/Request.pm
Module::Runtime is a faster module than Class::Load (even with
Class::Load::XS available) and is already available by our stack.
This was applied in #1164; but was erroneously undone in a later Pr.
> Replace Class::Load with Module::Runtime

- lib/Dancer2/Manual.pod
Nod to tushar on #dancer who was having trouble and lead me to spot this.
Hash::MultiValue's docs for get() say: "Note that this always returns the single
element as a scalar, regardless of its context".
> One should use get_all() to get multiple values.

- lib/Dancer2/Core/App.pm
- lib/Dancer2/Core/Request.pm
- t/forward_hmv_params.t
To resolve #1116 and #1245, the code in `App->make_forward_to` needs to ensure the "cached" HMV params in the current request are cloned into the new request.
However it doesn't make sense for our App class to know about the Request class internals. Instead, this PR refactors a large chunk of `App->make_forward_to` into a private method on Request. Within this;
* any `body_parameters` in the current request are copied into the new request.
* any extra params supplied to forward get added to `params`, `query_params` and `query_parameters`;
Note that extra params to forward are always considered to be **query** parameters, even if the method is POST.  The test cases included check this and that #1116 and #1245 are resolved.
> Bugfix Hash::MultiValue params on forward 

- lib/Dancer2/Manual.pod
Possibly needs moving elsewhere, maybe to `Manual.pod`?
> capture @xsawyerx async code example to doc

- lib/Dancer2/Core/Role/Template.pm
- lib/Dancer2/Template/TemplateToolkit.pm
- share/skel/config.yml
This reverts commit 8d0f3b105897283f3c28eade020f0e01798923f5.
See https://github.com/PerlDancer/Dancer2/issues/1307
Summary: that commit breaks [% %] tags in TT.
> Revert "Consistency for TemplateToolkit config"

- dist.ini
The ExtUtils::MakeMaker version was not set correctly
in the build_requires section of the META.yml file.
simple test
```
before> grep -B2 MakeMaker Dancer2-0.204004/META.yml
build_requires:
Capture::Tiny: '0.12'
ExtUtils::MakeMaker: '0'
--
Test::More: '0.92'
configure_requires:
ExtUtils::MakeMaker: '7.1101'
after> grep -B2 MakeMaker Dancer2-0.204004/META.yml
build_requires:
Capture::Tiny: '0.12'
ExtUtils::MakeMaker: '7.1101'
--
Test::More: '0.92'
configure_requires:
ExtUtils::MakeMaker: '7.1101'  
```
> Adjust dist.ini to set build_requires for ExtUtils::MakeMaker #1315

- lib/Dancer2/Manual.pod
Reference to `send_file` pointed to non-existent `send_file` module on CPAN instead of anchor on same page.
> Fix broken link to send_file

- lib/Dancer2/Core/App.pm
- t/prepare_app.t
I want to have a `prepare_app` which will be triggered on a `to_app`, just like what we manually do with `setup`, which is uncomfortable and not assured.
In order to introduce a `prepare_app` method in the caller, we need
to first make sure a user does not have one. This implements the
logic necessary to call it when it is available by including the
original class that was called, and then checking on it whether
the class has it, and if so, warns about it loudly.
Perhaps we should set a version or date?
We set the caller by attempting to reach level 2, which is the
correct level, but if you're calling App->new() manually (like
from a test), then you might have it at level 1, but if that's
not good, we can at least take level 0.
> Add preliminary prepare_app with guard

- lib/Dancer2/Core/Request.pm
X-Forwarded-Proto should be the preferred header to used to check if the
front end connection was HTTPS.  Proto is the de facto standard for
this, and is recommended in the deployment documentation.
If the -Protocol header is checked first, that means most setups that
only add a -Proto header will pass through a user provided -Protocol
header, allowing users to lie about the protocol used.
Ideally this would only check one header, and the reverse proxy would be
required to send that header.  Leaving this with the fallback behavior
for now for backwards compatibility.
> perfer X-Forwarded-Proto to prevent users lying

- share/skel/bin/+app.psgi
The plack middleware Deflate was activated by default, and
was not only in the commented section. A small issue as well
with the comment of the third block, which is not related
to Deflate middleware
> Issue in skeleton of file bin/+app.psgi

- lib/Dancer2/Manual.pod
- lib/Dancer2/Manual/Deployment.pod
#1383 
I agree with @szabgab. Allow the parser to link to where it likes. Accordingly with the POD manual, not URL means to link to a module manpage.
> remove search.perl.org links on docs

- lib/Dancer2/Manual.pod
There was already something there about the vars, but that seemed to be outdated and in general way less information.
> Add "Default template variables" section to manual

- lib/Dancer2/Core/Cookie.pm
- t/cookie.t
I had some issues disabling http_only cookies for the session cookie.
```YAML
session: YAML
engines:
session:
YAML:
cookie_name: session.id
is_http_only: 0
```
With a config like this the HttpOnly value would always get set in the cookie header string.
The HTTP::XSCookies module seems to handle strings different from numbers and does consider a string containing only '0' to be truthy.  This can be fixed by forcing boolean context on the value before passing it to the module. 
I added a fix for this and a test to make sure http_only can be disabled with a string.
> allow disabling of http only cookies using strings

- cpanfile
- lib/Dancer2/CLI/Command/gen.pm
File::Share provides its own dist_dir()/dist_file() which also work
in local source directories. Otherwise it will delegate to File::ShareDir
as usual.
Currently the `dancer2 gen` command will not work from the source directory
if there is no Dancer2 installed yet.
See https://perlmonks.org/?node_id=1209472
> Use File::Share on top of File::ShareDir

- lib/Dancer2/Core/Request.pm
Both Cookie::Baker and Cookie::Baker::XS return a string for the cookie
value, for which we then split on `&` for handling multiple values. The
alternative XS implementation for cookie crushing, HTTP::XSCookies does
the split, returning an arrayref.
Update the cookie object construction code to accept a string (which we
split), or an arrayref of values (which we leave alone). Allows use of
Cookie::Baker(::XS) or HTTP::XSCookies with minimal code to maintain.
Closes #1435.
> Handle XSCookies to return an arrayref of values

- cpanfile
Dancer2::Core::Request may call `psgi_flatten_without_sort` which was
added to HTTP::Headers::Fast in v0.21. Explicitly state that version
dependency in our cpanfile.
Closes #1445.
> Min version of HTTP::Headers::Fast in v0.21

- lib/Dancer2/Manual.pod
Fixed a number of broken links in the Dancer2 manual, raised in issue #1439 
I've also removed a reference to Dancer2::Session::Storable, as it doesn't seem to exist...
I wasn't sure how to actually test these links properly (I've tested them by viewing the file in the "Files changed" tab and they seem to be working).
> Fix broken links in Manual.pod

- lib/Dancer2/Core/App.pm
- t/log_levels.t
This hopefully fixes #1328. The logger callback log_cb which is set on the engines should include the code which checks that only messages which are at a sufficiently high log level are actually logged.
> Engines should respect log level

- lib/Dancer2/Config.pod
This is meant to fix PerlDancer/Dancer2#1492. Note that that issue
only mentions `Dancer2::Config::Object` being a non-existent module,
but since the `strict_config` property does not seem to exist at all
either, I just dropped the whole documentation subsection.
> Remove references to strict_config, Dancer2::Config::Object

- cpanfile
- lib/Dancer2/Core/App.pm
- lib/Dancer2/Core/Dispatcher.pm
Return::MultiLevel obscures the fact that returning across multiple
stack frames is very evil.  Rather than hide the evil we are doing, just
embed the stack breaking via a label and last.
This avoids a Return::MultiLevel dependency, which avoids pulling in
Scope::Upper, another module with too much magic in it.  It also is
slightly faster, although that is a very minor benefit.
> remove use of Return::MultiLevel, and implement stack frame jumping manually

- lib/Dancer2/Core/App.pm
- lib/Dancer2/Core/Route.pm
- lib/Dancer2/Manual.pod
- t/classes/Dancer2-Core-Route/match.t
- t/lib/TestTypeLibrary.pm
Hopefully this PR will generate some discussion as to how we would like to proceed with typed params. This code his been around for > 2 years and PR created after I was pinged about it by @cromedome.
Allows types to be specified in route param definitions allowing such things as:
```
get '/thing/:id[Int]' => sub {};
get '/thing/:id[Num]' => sub {};
```
In original issue @yanick suggested:
> Interesting venue to explore. We could even do something like (off-the-cuff pseudo-code below)
```
subtype UserId => as Int => validate { };  # don't remember the real Types::Tiny syntax
get '/api/user/!UserId' => sub { 
...;
param('UserId'); 
};
```
This is not currently possible in current implementation but could be added later.
See also @xsawyerx's …
> Route params with types

- lib/Dancer2.pm
- lib/Dancer2/Manual.pod
This is issue #1538 
Thank you @TimothyAlexisVass 
defined or assignment in docs should be defined without assignment
> Documentation fix (Named matching)

- t/issues/gh-811.t
This is issue #1541 
Fix test that was broken by switch to RFC 7231 (#1461).
My original PR pulled in an authordep on Dancer2::Session::Cookie, which of course caused a circular dependency on D2 itself, so that was removed.
> fix broken test that is skipped under CI

- lib/Dancer2/Tutorial.pod
Changes proposed:
- prefer `C<< >>` to using `=E` inside `C< >` for readability of raw pod
- consistent alignment of code and css in examples
- make sure all `=head` are followed by a blank line
- set encoding to utf8
- always break `or die` onto following line for consistency in examples
- remove unnecessary quotes around string before fat comma in examples
- some small changes to punctuation, mostly replacement of `-`
> various tutorial cleanups

- cpanfile
Avoids issue with Role::Tiny 2.000007 and Types::Standard undefined warnings
See: https://github.com/PerlDancer/Dancer2/issues/1515#issuecomment-518305067
> bump dep on Role::Tiny to 2.000008

- lib/Dancer2/Manual/Deployment.pod
- share/skel/cpanfile
This came up in discussing #1589 with @racke. This is really an independent fix from the Docker enhancement.
Make it easier to install the XS modules for the performance boost. Change the deployment pod to reflect this change. The Docker PR uses the new feature tag in `cpanfile` to install the XS modules when building the container image.
> Improve install/documentation of XS modules

- lib/Dancer2/Core/DSL.pm
- lib/Dancer2/Core/Request.pm
- lib/Dancer2/Manual.pod
- t/dsl/request_data.t
`request_data` will return the body of the request in either its
plain (body) form or deserialized (data) form.
This is needed as body_parameters is now a HMV which is suited
to represent parameters and not other forms of data.
Example:
In an app with a JSON serializer, we cannot use body_parameters
to distinguish between a body like '{"data":[]}' and '{}'.
> Added DSL keyword request_data.

- cpanfile
- lib/Dancer2/CLI.pm
The other approach discussed on #1602 - just removing the dependency on App::Cmd, so people using older perls can still install Dancer2, and have the `dancer2` minting tool exit with an explanatory message if the user doesn't have App::Cmd installed.
Leaves D2 installable for everyone, but with the minting tool not working until they install App::Cmd (until such time as we've replaced our use of that with e.g. MooX::Options).
This is an alternative approach to #1602 and #1603 - I'd expect only one of the PRs to be merged, depending on which we pick.
> Remove App::Cmd dep and have script/dancer2 bail if it's not installed

- dist.ini
- t/cli.t
The `Test::Compile` plugin to `Dist::Zilla` tries to build a compile test with all of our modules, except now that we have removed the requirement for `App::Cmd::Setup`, `App::Cmd::Setup` might not be installed, and our test suite fails. This PR addresses the problem in two ways:
* Excludes the `Dancer2::CLI` namespace from the automatic compile test generation
* Builds a compiles test specifically for the CLI that skips all if `App::Cmd::Setup` is not installed
> Fix broken tests following App::Cmd removal

- lib/Dancer2/CLI/Gen.pm
I tested this on a different machine than I developed on prior to release, and had some cruft that masked a bug when adding a Dockerfile to a new application. The dockerfile is located off of the dist dir, not off of the skel dir. This minor fix changes that.
I consider this a blocker for the release. Please review ASAP.
> Copy Dockerfile from the right spot

- cpanfile
I must have missed this when building out the git/docker integration. It's causing CI and cpantesters to fail.
> Add File::Which to Dancer2 dependencies

- cpanfile
- lib/Dancer2.pm
- lib/Dancer2/Core/Route.pm
- lib/Dancer2/Manual.pod
- lib/Dancer2/Manual/Keywords.pod
- t/classes/Dancer2-Core-Route/deprecated_param_keys.t
- t/classes/Dancer2-Core-Route/match.t
- t/disp_named_capture.t
- t/dsl/parameters.t
We can no longer install on 5.8 due to upstream dependencies, so I think it is time to admit defeat and bump our min dep. This also allows us to use defined-or and state variables.
Changes:
- use 5.10.1 in Dancer.pm
- add 5.10.1 dep to cpanfile
- remove all mentions of 5.10 from docs when describing named captures
- remove special-casing in code and tests for < 5.10
> Proposal: Set minimum Perl to 5.10.1

- lib/Dancer2.pm
- lib/Dancer2/DeprecationPolicy.pod
One last change to prep us for the release of 0.400000 - capture the deprecation policy in the docs.
Also we were missing a link to the git guide in the documentation map.
> Add deprecation policy to docs; link git guide

- lib/Dancer2/DeprecationPolicy.pod
When I reformatted the document, I failed to notice how vim butchered the module abstract. This restores it, and also fixes the wording.
Resolves #1657
> Fix the Dancer2::DeprecationPolicy abstract

- lib/Dancer2/Manual.pod
Per [this thread on Perlmonks](https://www.perlmonks.org/?node_id=11142558), the tutorial and manual were lacking the `gen` command in the `dancer2` application examples:
```
Successfully installed Dancer2-0.400000 (upgraded from 0.301004)
1 distribution installed
steve@maezi ~/scratch >dancer2 -a
Unknown option: a
Usage: dancer2 [-h] -h --help --man [subcommand] at /Users/steve/perl5/perlbrew/perls/perl-5.32.1/lib/site_perl/5.32.1/CLI/Osprey/Descriptive/Usage.pm line 329.
```
> Add 'gen' command to 'dancer2' runs

- Changes
- lib/Dancer2/Config.pod
- lib/Dancer2/Cookbook.pod
- lib/Dancer2/Core/Error.pm
- lib/Dancer2/Manual.pod
- lib/Dancer2/Tutorial.pod
- share/skel/environments/development.yml
- share/skel/environments/production.yml
- t/app.t
- t/config/config.yml
- t/config/environments/production.yml
- t/config/environments/staging.json
- t/config2/config.yml
- t/config_reader.t
- t/dispatcher.t
- t/dsl/content.t
- t/dsl/error_template.t
- t/error.t
- t/issues/gh-1070.t
- t/issues/gh-1098.t
- t/session_bad_client_cookie.t
- t/session_engines.t
- t/session_hooks.t
- t/session_hooks_no_change_id.t
- t/session_lifecycle.t
This is a rebase of @nunorc's work in #829.
I added another commit to make sure `show_errors` still works, but documented it's deprecated.
> (Rebased) rename show_errors as show_stacktrace

- .github/workflows/ci.yml
Minion is having some issues with the SQLite backend in GitHub actions presently. I don't have the time to diagnose a non-core issue right now, and the build failure emails are annoying, so away it goes.
> Remove failing module from GitHub actions config

- .github/workflows/ci.yml
- cpanfile
Moo now has a minimum version of Perl 5.14, and without Moo, we have nothing.
> Bump minimum version of Perl to 5.14

- .github/workflows/ci.yml
- dist.ini
Minimum "supported" Perl version should be 5.20 now. Make sure we run tests against the most current production version too.
> Update tests for minimum, current Perl version

- .github/workflows/ci.yml
GitHub Actions, regardless of what we tell it, still insists on installing the incorrect version of Module::Pluggable. Instead, we'll hit it with a really big hammer and force it to install.
This can be removed once the author fixes the issue installing Module::Pluggable as root.
I don't like doing this but I also don't like holding up a release because tests aren't passing.
> Force install Module::Pluggable so CI can run

- lib/Dancer2/Template/TemplateToolkit.pm
- t/lib/Dancer2/Template/TemplateToolkitFoo.pm
- t/lib/TemplateFoo.pm
- t/template.t
Enable use of different Template::Toolkit base class in `Dancer2::Template::TemplateToolkit` (see #1722)
> Enable use of a different Template::Toolkit base class (#1722)

- lib/Dancer2/CLI/Gen.pm
This... is kinda fluff, I admit. Don't add files typically used to package applications for CPAN when generating a new app.
If you use a custom app skeleton, this could be mute. But if you're like a lot of people and use the default skeleton, this is one little bit of less work after the fact.
I considered making this the default but didn't want to change what is accepted default behavior.
> Don't create CPAN package files when generating new apps

- lib/Dancer2/Plugin.pm
Test::Pod::Coverage will check for pod on all methods, including private methods, unless you tell it otherwise. This is probably not what you want. Document how to omit pod coverage testing of private methods.
Fixes #1342
> Document skipping private methods in plugin pod tests

- lib/Dancer2/Core/App.pm
- lib/Dancer2/Manual.pod
- t/hooks.t
This adds a new type of hook that is called in the event of an exception in a hook. Because of its nature it's a bit more complicated than a normal hook, in particular because it could result in recursive calling.
Because this hook can be called in quite a variety of ways during response handling, and because the current hook exception behavior is quite blunt, I also wanted to make it quite flexible in terms of controlling what happens. In particular, I wanted to be able to change the default response in the event of an exception in a hook. The comments in the code and the documentation should all be self-explanatory in this regard.
For #1737
> Add new hook for exceptions in hooks (#1737)
