PerlDancer/Dancer2

lib/Dancer2/Core/Request.pm
Fix small typo in documentation.
=> Fix typo in docs

lib/Dancer2/Plugin.pm
See https://github.com/PerlDancer/Dancer2/issues/1002 for more
information. Not much of a fix, just wanted to make it a little more
clear in the docs that this is needed.
=> Added $dsl-> to execute calls, per #1002.

lib/Dancer2/Core/Error.pm, t/issues/gh-1070.t
This is an alternative fix for GH PR #1070
=> _html_encode $self->message in default_error_page

README.mkdn, lib/Dancer2.pm
Remove duplicate entry from contributors list.
=> Remove duplicate entry from contributors list

lib/Dancer2/Manual.pod
=> document exporting the utf8 pragma

Changes, lib/Dancer2/Core/App.pm, lib/Dancer2/Core/Role/HasLocation.pm, lib/Dancer2/Plugin.pm, lib/Dancer2/Plugins.pod, share/skel/public/+dispatch.cgi, share/skel/public/+dispatch.fcgi, t/auto_page.t, t/classes/Dancer2-Core-Route/match.t, t/dispatcher.t, t/mime.t, t/plugin_register.t, t/plugin_syntax.t, t/template.t, xt/perlcritic.rc
=> Fix spelling mistakes detected by codespell

lib/Dancer2/Core/App.pm, lib/Dancer2/Plugin.pm, t/lib/PoC/Plugin/Polite.pm, t/lib/poc2.pm, t/plugin2/basic-2.t
Plugin2 requires plugins to be in the Dancer2 namespace. This is an attempt to liberate that..
Consider this "work in progress" - wanted to get this out there and get some discussions going.
=> Plugins in all the namespaces

lib/Dancer2/Manual.pod
Small POD fix in Dancer2::Manual.
=> Fix POD in documentation

lib/Dancer2/Core/Request.pm, lib/Dancer2/Manual.pod
Apropos Kadir's question to the users list, I suggest a number of changes to the documentation of `params` and friends, to make the merge behaviour (and its dangers) clearer.
=> Improve docs about params

cpanfile, lib/Dancer2/Core/App.pm, lib/Dancer2/Core/Cookie.pm, lib/Dancer2/Core/DSL.pm, lib/Dancer2/Core/Error.pm, lib/Dancer2/Core/Request.pm, lib/Dancer2/Core/Role/SessionFactory.pm, lib/Dancer2/Core/Role/Template.pm, lib/Dancer2/Core/Route.pm, lib/Dancer2/Core/Runner.pm
any reason not to use Ref::Util in all ref checks in Core?
=> use Ref::Util in Core

lib/Dancer2/Core/Role/Template.pm
Hi,
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> - Fixed possible typo in the pod for package Dancer2::Core::Role::Template.

lib/Dancer2/Tutorial.pod
Hi Team Dancer,
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Fixed broken link to Bottle python framework in the pod for Dancer2::Tutorial

lib/Dancer2/Manual/Migration.pod
Hi Team Dancer,
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Fixed broken link to methoda in the pod for Dancer2::Manual::Migration.

lib/Dancer2.pm
I don't need to show up in the authors list twice
=> remove duplicate author name

lib/Dancer2/Manual/Deployment.pod
=> Use the correct URL for HAProxy.

lib/Dancer2/Cookbook.pod
Hi Team Dancer2,
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Tidied up pod for Cookbook.

lib/Dancer2/CLI/Gen.pm, share/docker/Dockerfile, share/skel/cpanfile
This is the same PR as #1589 with the same features and syntax, just reimplemented for the new CLI.
=> Generate a Dockerfile when creating a new app

lib/Dancer2/Tutorial.pod
Semicolons are not special in YAML and certainly not comments.
=> Fix YAML example in the tutorial

lib/Dancer2.pm
This pull request contains spelling and grammar fixes, as well as a small fix to the gen app command in the docs.
=> Fix spelling and grammar to docs

README.mkdn, lib/Dancer2.pm
Adding @GeekRuthie as a core dev.
=> Assimilate GeekRuthie

Contributing.md
This already covered a lot of ground, and now it covers even more:
- Itemize new ways to contribute
- Reminds people to run tests
- Reasons we may request changes to/reject pull requests
A few revisions to language throughout, and in preparation of other upcoming changes, replaced master with main, and fixed some nagging http: links.
=> Update the contribution guidelines

Changes
=> rename `master` to be `main`.
